Add Azure Key vault support
radius-project/radius pull request #185
Opened 2021-04-08 18:46 UTC by vinayada1

1. Create a KV
2. Create a managed identity per container
3. Grant KV access to the MI using RBAC
4. Create pod identity binding the MI to a pod label
5. Modify container k8s to use the aadpodidentity label

Fixes #125 , #334

2021-04-27 01:17 UTC, rynowak requested changes
It's awesome to see this come together E2E. There are some design challenges here that we should talk through.

2021-04-29 01:21 UTC, rynowak reviewed
This is very much on track, just a few smaller comments here to address.

2021-05-04 06:17 UTC, AaronCrawfis requested changes

2021-05-04 16:39 UTC, rynowak approved these changes

2021-05-04 23:55 UTC, AaronCrawfis approved these changes

2021-05-05 18:38 UTC, merged