Interactive env init kubernetes prompts environment name
radius-project/radius pull request #2150
Opened 2022-03-31 18:10 UTC by mhaveliwala1

# Description

Previously, `rad env init kubernetes -i` would not prompt the user to set environment name. This PR aims to fix this behavior and make the process more interactive.

## Issue reference

Please reference the issue this PR will close: #2141 

## Checklist

Please make sure you've  completed the relevant tasks for this PR, out of the following list:

* [ ] Code compiles correctly
* [ ] Adds necessary unit tests for change
* [ ] Adds necessary E2E tests for change
* [ ] Unit tests passing
* [ ] Extended the documentation / Created issue for it

2022-03-31 20:42 UTC, bjoginapally approved these changes

2022-04-01 15:48 UTC, amanbha approved these changes

2022-04-01 16:52 UTC, jkotalik requested changes
Once this is fixed, LGTM

2022-04-01 22:36 UTC, jkotalik approved these changes

2022-04-01 22:40 UTC, merged