Add healthz endpoint metrics
radius-project/radius pull request #2272
Opened 2022-04-28 02:54 UTC by bjoginapally

# Description

Part of series to add geneva metrics

## Issue reference

Please reference the issue this PR will close: #_[issue number]_

## Checklist

Please make sure you've  completed the relevant tasks for this PR, out of the following list:

* [ ] Code compiles correctly
* [ ] Adds necessary unit tests for change
* [ ] Adds necessary E2E tests for change
* [ ] Unit tests passing
* [ ] Extended the documentation / Created issue for it

2022-04-28 18:49 UTC, youngbupark submitted a review, later dismissed

2022-05-04 02:18 UTC, shalabhms requested changes

2022-05-05 16:30 UTC, shalabhms approved these changes

2022-05-05 16:46 UTC, merged

2022-05-08 22:22 UTC, youngbupark reviewed
@bjoginapally Please review my comments and address them.