Improving pagination logic in list environments
radius-project/radius pull request #2319
Opened 2022-05-09 18:00 UTC by ytimocin

# Description

Improvements to the pagination logic in list environments.

Addressing the comments in this already-merged PR: https://github.com/project-radius/radius/pull/2280

## Issue reference

Please reference the issue this PR will close: #2238 

## Checklist

Please make sure you've  completed the relevant tasks for this PR, out of the following list:

* [x] Code compiles correctly
* [x] Adds necessary unit tests for change
* [ ] Adds necessary E2E tests for change
* [x] Unit tests passing
* [x] Extended the documentation / Created issue for it

2022-05-09 22:27 UTC, youngbupark requested changes

2022-05-16 20:19 UTC, jkotalik approved these changes

2022-05-16 22:19 UTC, kachawla approved these changes

2022-05-17 02:40 UTC, youngbupark approved these changes
/lgtm

2022-05-17 16:59 UTC, merged