Create or update container resource in an async way
radius-project/radius pull request #2551
Opened 2022-06-09 00:57 UTC by ytimocin

Please see a list of things to do here: #2541 

This PR creates container resource and its async PUT endpoint. I have some questions in the PR that I would like to talk to anyone who would be interested.

One question is that when we are returning the headers should we provide a full URL or just the routing scope? Please see the attached screenshot.
![image](https://user-images.githubusercontent.com/5220939/173159608-fdbe554a-cf45-488e-8262-ccb2c37d280e.png)

I will update the Postman collection and share with the team.

# Description
Creating a new or updating an existing container in an async way.

## Issue reference
Please reference the issue this PR will close: #2541 

## Checklist

Please make sure you've  completed the relevant tasks for this PR, out of the following list:

* [x] Code compiles correctly
* [x] Adds necessary unit tests for change
* [ ] Adds necessary E2E tests for change
* [x] Unit tests passing
* [x] Extended the documentation / Created issue for it

2022-06-11 00:05 UTC, youngbupark requested changes

2022-06-11 00:10 UTC, youngbupark requested changes

2022-06-15 02:32 UTC, youngbupark requested changes

2022-06-15 17:35 UTC, youngbupark requested changes

2022-06-16 16:57 UTC, shalabhms approved these changes

2022-06-16 17:51 UTC, youngbupark approved these changes
Once you complete DELETE async operation, please refactor to remove potential duplicated codes.

2022-06-16 21:11 UTC, merged