Async deletion of a container resource
radius-project/radius pull request #2619
Opened 2022-06-17 19:16 UTC by ytimocin

# Description
This is to add async deletion for a container resource.

~~Note: More tests will be added.~~

## Issue reference
Please reference the issue this PR will close: #2608 

## Checklist

Please make sure you've  completed the relevant tasks for this PR, out of the following list:

* [x] Code compiles correctly
* [x] Adds necessary unit tests for change
* [ ] Adds necessary E2E tests for change
* [x] Unit tests passing
* [x] Extended the documentation / Created issue for it

2022-06-20 20:03 UTC, youngbupark requested changes

2022-06-21 04:50 UTC, shalabhms approved these changes

2022-06-21 17:18 UTC, youngbupark approved these changes

2022-06-21 17:30 UTC, merged

2022-06-22 20:40 UTC, jkotalik reviewed
LGTM