Adding Options to the BaseAsyncController
radius-project/radius pull request #2805
Opened 2022-07-05 21:14 UTC by ytimocin

# Description
Using Options struct in the BaseAsyncController instead of passing parameters one by one.

## Issue reference

Please reference the issue this PR will close: #_[issue number]_

## Checklist

Please make sure you've  completed the relevant tasks for this PR, out of the following list:

* [x] Code compiles correctly
* [ ] Adds necessary unit tests for change
* [ ] Adds necessary E2E tests for change
* [x] Unit tests passing
* [x] Extended the documentation / Created issue for it

2022-07-05 21:19 UTC, youngbupark approved these changes

2022-07-05 21:41 UTC, jkotalik approved these changes

2022-07-05 21:49 UTC, shalabhms approved these changes

2022-07-05 22:49 UTC, youngbupark requested changes

2022-07-06 01:56 UTC, youngbupark approved these changes
I left some nitpick comments. overall LGTM.

2022-07-06 02:08 UTC, kachawla approved these changes

2022-07-06 18:23 UTC, merged