Generic delete backend controller
radius-project/radius pull request #2900
Opened 2022-07-13 17:55 UTC by ytimocin

# Description
Generic delete backend controller for CoreRP.

## Issue reference
Please reference the issue this PR will close: #2870 

## Checklist

Please make sure you've  completed the relevant tasks for this PR, out of the following list:

* [ ] Code compiles correctly
* [ ] Adds necessary unit tests for change
* [ ] Adds necessary E2E tests for change
* [ ] Unit tests passing
* [ ] Extended the documentation / Created issue for it

2022-07-13 17:59 UTC, youngbupark approved these changes
Please validate it locally before merging.

2022-07-14 16:26 UTC, youngbupark requested changes

2022-07-14 18:27 UTC, mishrapratikshya approved these changes

2022-07-14 18:35 UTC, jkotalik approved these changes

2022-07-14 18:43 UTC, youngbupark approved these changes

2022-07-14 18:44 UTC, merged