Renaming test resources to prevent collisions
radius-project/radius pull request #3021
Opened 2022-07-19 21:01 UTC by willdavsmith

# Description

_Please explain the changes you've made._

## Issue reference

Please reference the issue this PR will close: #_[issue number]_

## Checklist

Please make sure you've  completed the relevant tasks for this PR, out of the following list:

* [ ] Code compiles correctly
* [ ] Adds necessary unit tests for change
* [ ] Adds necessary E2E tests for change
* [ ] Unit tests passing
* [ ] Extended the documentation / Created issue for it

2022-07-19 23:51 UTC, vinayada1 approved these changes

2022-07-19 23:56 UTC, jkotalik requested changes
If I wanted to add a test, how would I figure out this naming pattern? Just trying to make sure I as a dev can add a test that follows this scheme.

2022-07-20 16:01 UTC, jkotalik approved these changes

2022-07-20 16:13 UTC, ytimocin approved these changes

2022-07-20 17:42 UTC, merged