Refactor PUT and DELETE controllers with generic operation controller
radius-project/radius pull request #3512
Opened 2022-09-08 00:44 UTC by youngbupark

# Description

This PR defines Operation Generic struct to support multiple data models and reduce the duplicated code to handle the different models.

## Issue reference

#3513

## Checklist

Please make sure you've  completed the relevant tasks for this PR, out of the following list:

* [ ] Code compiles correctly
* [ ] Adds necessary unit tests for change
* [ ] Adds necessary E2E tests for change
* [ ] Unit tests passing
* [ ] Extended the documentation / Created issue for it

2022-09-15 01:12 UTC, rynowak requested changes

2022-09-15 15:54 UTC, ytimocin approved these changes

2022-09-17 01:43 UTC, rynowak reviewed
This is looking at a lot better, just 1-2 questions.

2022-09-19 17:26 UTC, rynowak approved these changes

2022-09-19 22:20 UTC, shalabhms approved these changes

2022-09-20 00:08 UTC, rynowak approved these changes
:shipit:

2022-09-20 17:13 UTC, merged