`rad env create`
radius-project/radius pull request #3516
Opened 2022-09-08 16:13 UTC by sk593

# Description

need to add unit tests and resource group checks and clean up some code but basic implementation is done

## Issue reference

Fixes: #3433

## Checklist

Please make sure you've  completed the relevant tasks for this PR, out of the following list:

* [ ] Code compiles correctly
* [ ] Adds necessary unit tests for change
* [ ] Adds necessary E2E tests for change
* [ ] Unit tests passing
* [ ] Extended the documentation / Created issue for it

2022-09-27 22:56 UTC, AaronCrawfis requested changes
Couple small description updates.

2022-10-06 17:20 UTC, AaronCrawfis requested changes
There's an edge case I'm hitting when `config.yaml` does not have a scope set (got into this state by running `rad workspace create`):

```yaml
workspaces:
  default: aacrawfi
  items:
    aacrawfi:
      connection:
        context: aacrawfi
        kind: kubernetes
```

This leads to:

```bash
PS D:\Repos\project-radius\radius\cmd\rad> .\rad.exe env create testenv
Error: '' is not a valid resource id
```

Is there a way we can make this error message a little more useful? Or check that a scope is set in the users workspace. I would expect this to be:

```bash
PS D:\Repos\project-radius\radius\cmd\rad> .\rad.exe env create testenv
Error: no resource group specified or set as default. Specify a resource group with '--group' and try again.
```

2022-10-06 21:01 UTC, ytimocin approved these changes
other than Aaron's comments on documentation lgtm

2022-10-07 00:09 UTC, AaronCrawfis approved these changes

2022-10-07 15:29 UTC, merged