rad group commands
radius-project/radius pull request #3705
Opened 2022-09-14 15:39 UTC by nithyatsu

# Description

Support rad group commands compliant with new cli framework and using ucp generated clients. 
Also brings in UCP swagger + auto generated clients since its a dependency from https://github.com/project-radius/radius/issues/3510

## Issue reference
Fixes: #3435 

## Checklist

Please make sure you've  completed the relevant tasks for this PR, out of the following list:

* [X] Code compiles correctly
* [x] Adds necessary unit tests for change
* [x] Adds necessary E2E tests for change
* [x] Unit tests passing
* [ ] Extended the documentation / Created issue for it

2022-09-14 17:51 UTC, AaronCrawfis requested changes
Added some comments on CLI descriptions. Biggest question is if we should refer to them as "RAD resource groups" or just "resource groups", given they're a UCP concept and not a Radius concept (using the definition of Radius being the RPs). We can still refer to them as "RAD" or "Radius" resource groups if we want to refer to Radius as the project & entire control plane.

2022-09-14 21:58 UTC, youngbupark requested changes

2022-09-15 18:14 UTC, bjoginapally approved these changes

2022-09-21 17:02 UTC, AaronCrawfis requested changes
Couple notes on text

2022-09-21 21:50 UTC, AaronCrawfis approved these changes

2022-09-22 17:34 UTC, youngbupark approved these changes
I left two comments. I do see this is missing comments for public functions. I strongly recommend to add comments for public functions (it is fine to not have it in test)

2022-09-22 18:23 UTC, merged