RedisCache: Schema update to add recipe
radius-project/radius pull request #3710
Opened 2022-09-14 20:41 UTC by mishrapratikshya

# Description

Added recipe to the rediscache swagger file and updated the data model and client.
Sample Model can be found: #3635 
## Issue reference

Fixes: #3637 

## Checklist

Please make sure you've  completed the relevant tasks for this PR, out of the following list:

* [x] Code compiles correctly
* [x] Adds necessary unit tests for change
* [ ] Adds necessary E2E tests for change
* [x] Unit tests passing
* [ ] Extended the documentation / Created issue for it

2022-09-14 20:45 UTC, kachawla reviewed
Can you please add link to the corresponding app model for reference in the description?

2022-09-14 21:04 UTC, shalabhms requested changes

2022-09-14 21:12 UTC, kachawla reviewed
Are you planning to update the data model in a separate PR?

2022-09-14 21:20 UTC, AaronCrawfis submitted a review, later dismissed

2022-09-15 01:25 UTC, shalabhms approved these changes

2022-09-15 20:10 UTC, shalabhms approved these changes

2022-09-15 20:17 UTC, merged