add new CLI command: rad env show
radius-project/radius pull request #378
Opened 2021-05-17 14:07 UTC by emily-potyraj

This PR also makes minor updates to the Contributing Code section of our docs: removes "$" char from code blocks now that our docs have "Copy" button. 
_______

### rad env show
```
% rad env show --help
Show RAD environment details

Usage:
  rad env show [flags]

Flags:
  -e, --env string   The environment name
  -h, --help         help for show

Global Flags:
      --config string   config file (default is $HOME/.rad/config.yaml)
```

Default behavior with no env specified by user is to return info for the current default env: 
```
% rad env show         
Using config file: /Users/emilypotyraj/.rad/config.yaml

name: azure
kind: azure
subscriptionid: 66d1209e-1382-45d3-99bb-650e6bf63fc0
resourcegroup: em-0512-v1
clustername: radius-aks-pbw4gi2t3stss
```

Users can also use the `-e` (`-env`) flag to specify an env from their config file 
```
% rad env show --config $HOME/.rad/config.yaml -e local
Using config file: /Users/emilypotyraj/.rad/config.yaml

name: local
kind: local
```
_________

Btw, output format of `rad env show` is intended to match that of `rad env list`:
```
% rad env list --config $HOME/.rad/config.yaml
Using config file: /Users/emilypotyraj/.rad/config.yaml

default: azure
items:
    azure:
        clustername: radius-aks-pbw4gi2t3stss
        kind: azure
        resourcegroup: em-0512-v1
        subscriptionid: 66d1209e-1382-45d3-99bb-650e6bf63fc0
    local:
        kind: local
```

2021-05-17 16:00 UTC, AaronCrawfis requested changes

2021-05-18 00:56 UTC, rynowak approved these changes
LGTM once you and @aaroncrawfis are happy with docs

2021-05-19 15:55 UTC, AaronCrawfis approved these changes

2021-05-19 19:06 UTC, kachawla approved these changes

2021-05-20 22:58 UTC, merged