Add credential resource to ucp
radius-project/radius pull request #3936
Opened 2022-09-27 20:55 UTC by nithyatsu

# Description

Add credentials as a resource

## Issue reference

Fixes: #3589

## Checklist

Please make sure you've  completed the relevant tasks for this PR, out of the following list:

* [x] Code compiles correctly
* [ ] Adds necessary unit tests for change
* [ ] Adds necessary E2E tests for change
* [ ] Unit tests passing
* [ ] Extended the documentation / Created issue for it

2022-09-29 00:14 UTC, ytimocin approved these changes

2022-09-29 15:07 UTC, rynowak requested changes

2022-10-04 17:14 UTC, bjoginapally approved these changes

2022-10-04 20:18 UTC, rynowak approved these changes

2022-10-05 23:28 UTC, youngbupark approved these changes
/lgtm

2022-10-06 01:26 UTC, merged