doc updates for v0.2.0
radius-project/radius pull request #488
Opened 2021-06-04 21:06 UTC by emily-potyraj

- fixes a couple straggler references to the old CLI format
- adds language to the bindings language to attempt to answer questions users might have about them
- Radius-managed v. user-managed examples: add code directly to the page for users to read (instead of just downloadable). 
- minor language nit-picks 
- rename state store component in examples so there's no dash character in the name ("inventory-store" --> "inventorystore") 
  - "Code="DeploymentFailed" ... "inventory-storedf40386cf is not a valid storage account name. Storage account name must be between 3 and 24 characters in length and use numbers and lower-case letters only." 

btw, we've got 3 sections that describe Bindings functionality. I attempted to lean into explaining bindings in the framework of each of those 3 contexts.   
- /concepts/overview-concept/#bindings 
- /app-model/components-model/#binding-configuration
- /app-model/bindings-model/

2021-06-06 20:30 UTC, jkotalik approved these changes
Your writing is 🔥

2021-06-07 14:04 UTC, AaronCrawfis requested changes

2021-06-10 18:32 UTC, AaronCrawfis requested changes

2021-06-11 17:05 UTC, AaronCrawfis requested changes

2021-06-11 20:23 UTC, jkotalik approved these changes

2021-06-16 22:20 UTC, rynowak approved these changes
:shipit: after addressing comments

2021-07-08 01:18 UTC, AaronCrawfis approved these changes

2021-07-12 21:56 UTC, merged