Adding retries to AWS resource deletion
radius-project/radius pull request #5337
Opened 2023-03-23 23:34 UTC by willdavsmith

# Description

* Adding retries to the delete logic for AWS resources in functional tests

## Issue reference

Fixes: https://github.com/project-radius/radius/issues/5277

## Checklist

Please make sure you've  completed the relevant tasks for this PR, out of the following list:

* [ ] Code compiles correctly
* [ ] Adds necessary unit tests for change
* [ ] Adds necessary E2E tests for change
* [ ] Unit tests passing
* [ ] Extended the documentation / Created issue for it

2023-03-29 16:35 UTC, youngbupark approved these changes

2023-03-30 16:38 UTC, youngbupark requested changes

2023-04-11 16:58 UTC, vinayada1 approved these changes

2023-04-11 21:32 UTC, youngbupark approved these changes
Please add the comment to ensure that the deletion is using cloudcontrol api instead of ucp proxied apis.

2023-04-12 05:53 UTC, merged