Updating the release process doc
radius-project/radius pull request #5370
Opened 2023-03-30 19:42 UTC by ytimocin

# Description

Updates to the release process doc.

## Issue reference
Fixes: #issue_number

## Checklist

Please make sure you've  completed the relevant tasks for this PR, out of the following list:

* [ ] Code compiles correctly
* [ ] Adds necessary unit tests for change
* [ ] Adds necessary E2E tests for change
* [ ] Unit tests passing
* [ ] Extended the documentation / Created issue for it

2023-06-08 17:13 UTC, AaronCrawfis approved these changes

2023-06-16 16:23 UTC, AaronCrawfis requested changes
Couple small things

2023-06-16 17:20 UTC, AaronCrawfis approved these changes

2023-06-16 18:14 UTC, nithyatsu approved these changes

2023-06-16 18:16 UTC, merged