Redis resource default recipe experience implementation
radius-project/radius pull request #5509
Opened 2023-05-02 22:21 UTC by sk593

# Description

This work moves redis caches over to the agreed upon default recipe experience 

## Issue reference

Partially Fixes: radius-project/radius#6446

## Checklist

Please make sure you've  completed the relevant tasks for this PR, out of the following list:

* [ ] Code compiles correctly
* [ ] Adds necessary unit tests for change
* [ ] Adds necessary E2E tests for change
* [ ] Unit tests passing
* [ ] Extended the documentation / Created issue for it

2023-05-05 05:55 UTC, AaronCrawfis requested changes
Could we use a feature branch for the work to move to the default recipe experience? I'd like to avoid a situation where only some of our resources have the new default experience while others still use the old experience.

Ideally we can make all the changes and then merge them all into `main` at once.

2023-05-10 02:55 UTC, rynowak requested changes
Looks like a few of these changes broke tests

2023-05-10 16:06 UTC, rynowak approved these changes
:shipit: from me

2023-05-10 17:47 UTC, shalabhms approved these changes

2023-05-10 18:09 UTC, merged