Using dev flag during rad init to install dev recipes
radius-project/radius pull request #5526
Opened 2023-05-05 00:46 UTC by ytimocin

# Description
This is the first PR of the `rad init --dev` experience update. This PR adds the following:
1. Sets UseDevRecipes to false in all conditions
2. Adds the recipe installation to the `rad init --dev` command
3. Unit tests

After this PR, the only way to install dev recipes will be by using the `rad init --dev` command.

## Issue reference
Fixes: radius-project/core-team#1173 

## Checklist

Please make sure you've  completed the relevant tasks for this PR, out of the following list:

* [x] Code compiles correctly
* [x] Adds necessary unit tests for change
* [x] Adds necessary E2E tests for change
* [x] Unit tests passing
* [x] Extended the documentation / Created issue for it

2023-05-13 20:27 UTC, kachawla reviewed
I think it'll help to write a short summary of what the new expected user experience is. For example -

- Expected name of dev recipes
- Platforms supported
- User can override them, unregister them

2023-05-16 22:33 UTC, shalabhms requested changes
Thanks for resolving comments. Requesting for pending changes.

2023-05-18 17:56 UTC, shalabhms approved these changes
/lgtm. Thanks for resolving comments.

2023-05-19 22:28 UTC, rynowak approved these changes

2023-05-21 07:12 UTC, merged