Namespace Splitting: Phase 1 : new types
radius-project/radius pull request #5557
Opened 2023-05-12 17:58 UTC by lakshmimsft

# Description

CADL, namespace, type updates for [ADO User Story - Phase 1](https://dev.azure.com/azure-octo/Incubations/_workitems/edit/7378) 

#3499 

Fixes: Part of #3499 

## Checklist

Please make sure you've  completed the relevant tasks for this PR, out of the following list:

* [ ] Code compiles correctly
* [ ] Adds necessary unit tests for change
* [ ] Adds necessary E2E tests for change
* [ ] Unit tests passing
* [ ] Extended the documentation / Created issue for it

2023-05-13 19:10 UTC, kachawla reviewed
Is it possible to break this PR down or is everything dependent on each other? Breaking it down into smaller PR will make it easier to review and validate the changes.

2023-05-16 19:36 UTC, shalabhms requested changes
Requesting changes to extract to common.cadl and importing it in the main.cadl files.

2023-05-17 18:36 UTC, shalabhms approved these changes
Thanks Lakshmi for resolving my comments. /lgtm , nothing blocking.

2023-05-18 01:42 UTC, vishwahiremat approved these changes

2023-05-18 01:43 UTC, merged