rad group switch output
radius-project/radius pull request #7488
Opened 2024-04-11 10:28 UTC by gpltaylor

# Description
rad cli group switch output to display success message when switching output to a group

## Type of change
- This pull request fixes a bug in Radius and has an approved issue (issue link required).

Fixes: #7395

2024-04-11 11:45 UTC, gpltaylor commented
UPDATE: I will look into the test. I did some manual testing but I didn't run tests locally as the change was insignificant... We live and learn.

<img width="773" alt="image" src="https://github.com/radius-project/radius/assets/3308167/6fb8f91c-b660-4c4c-b13d-864e275c1bed">

2024-04-11 15:27 UTC, gpltaylor commented
Updated and tests running successfully locally.

<img width="638" alt="image" src="https://github.com/radius-project/radius/assets/3308167/aa001f23-f0fc-43a7-b02f-293d4819ca6a">

2024-04-11 18:08 UTC, rynowak commented on pkg/cli/cmd/group/groupswitch/switch_test.go
> +				Output:               outputSink,
Can you add an assert below about the output?

Here's an example you can borrow from: https://github.com/radius-project/radius/blob/main/pkg/cli/cmd/app/delete/delete_test.go#L280

2024-04-11 18:09 UTC, rynowak requested changes
Could you update the test to verify the console output? Other than that change looks great!

2024-04-12 15:29 UTC, ytimocin approved these changes, later dismissed
LGTM. Thanks for your contribution!

2024-04-12 15:29 UTC, ytimocin commented on pkg/cli/cmd/group/groupswitch/switch.go
> +
nit: extra line can be removed

2024-04-12 15:30 UTC, ytimocin commented
You also need a rebase/merge with the main branch.

2024-04-14 16:45 UTC, rynowak approved these changes
Awesome, thanks @gpltaylor

2024-04-14 18:18 UTC, gpltaylor commented
@rynowak hows this looking? 
Let me know if you need anything else.

2024-04-14 18:42 UTC, rynowak commented
Th

> @rynowak hows this looking? Let me know if you need anything else.

I'm merging this now. Thanks again.

2024-04-14 18:42 UTC, merged