Making necessary changes in the running-functional-tests document. Also doing some cleanup.
radius-project/radius pull request #8087
Opened 2024-11-25 06:44 UTC by ytimocin

# Description
Making necessary changes in the running-functional-tests document. Also doing some cleanup:
1. Removed unnecessary environment variables from the workflows.

## Type of change
- This pull request is a minor refactor, code cleanup, test improvement, or other maintenance task and doesn't change the functionality of Radius (issue link optional).
Fixes: #issue_number

## Contributor checklist
Please verify that the PR meets the following requirements, where applicable:

- [ ] An overview of proposed schema changes is included in a linked GitHub issue.
- [ ] A design document PR is created in the [design-notes repository](https://github.com/radius-project/design-notes/), if new APIs are being introduced.
- [ ] If applicable, design document has been reviewed and approved by Radius maintainers/approvers.
- [ ] A PR for the [samples repository](https://github.com/radius-project/samples) is created, if existing samples are affected by the changes in this PR.
- [ ] A PR for the [documentation repository](https://github.com/radius-project/docs) is created, if the changes in this PR affect the documentation or any user facing updates are made.
- [ ] A PR for the [recipes repository](https://github.com/radius-project/recipes) is created, if existing recipes are affected by the changes in this PR.

2024-11-25 16:48 UTC, kachawla reviewed
Had left some comments on previous version of this PR here: https://github.com/radius-project/radius/pull/8069

2024-11-25 18:32 UTC, ytimocin commented
> What's the motivation for changing file name style?

I think the naming convention for **sh** files is underscores, dashes, or all words together. We use camel case for now. We use both underscores and dashes.

Ref: https://google.github.io/styleguide/shellguide.html#source-filenames.

I was creating new sh files for cloud and non-cloud, so I wanted to give them new names that would also be consistent with other names in our codebase.

That being said, we need to decide if we want to use underscores or dashes because we have both. We only had one camel-case and I changed that.

2024-11-26 18:28 UTC, ytimocin commented on .github/workflows/functional-test-cloud.yaml
> -          # AZURE_MSSQL_PASSWORD
I see these are not being used anymore.

2024-11-26 18:28 UTC, ytimocin commented on .github/workflows/functional-test-cloud.yaml
> -          RADIUS_SAMPLES_REPO_ROOT: ${{ github.workspace }}/samples
This is only being used in the noncloud tests.

2024-11-26 18:28 UTC, ytimocin commented on .github/workflows/functional-test-noncloud.yaml
> -          SSL_CERT_FILE: ${{ steps.create-local-registry.outputs.temp-cert-dir }}/certs/${{ env.LOCAL_REGISTRY_SERVER }}/client.crt
Not being used.

2024-11-26 18:28 UTC, ytimocin commented on test/testrecipes/test-terraform-recipes/README.md
reformat

2024-12-12 15:12 UTC, brooke-hamilton requested changes
I was able to get all five services running with a debugger following these instructions. 🎆 

A helpful note in troubleshooting would be to say that after launching the debugger, five items should be visible in the VS Code call stack panel (in the debugging tab): 
- Launch Deployment Engine
- Launch Dynamic RP
- Launch Applications RP
- Launch Controller
- Launch UCP

Initially, I had a failure because I was deploying a kind cluster using the instructions in our docs site to map ports, but those ports were conflicting with the ports the debugger was attaching to, causing 503 errors. This became apparent when I realized that the Launch Applications RP debugging configuration was failing and would disappear from the list of processes.

2024-12-12 16:44 UTC, brooke-hamilton commented on docs/contributing/contributing-code/contributing-code-tests/running-functional-tests.md
> +1. Required environment variables:
Where are the values for these found so that they can be set?

2025-01-02 18:20 UTC, kachawla commented on .github/workflows/functional-test-noncloud.yaml
> -          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
Where does [this](https://github.com/radius-project/radius/blob/main/test/testutil/testutil.go#L139) gets set?

2025-01-02 18:20 UTC, kachawla commented on test/execute-functional-tests-cloud.sh
> +if [ -z "$BICEP_RECIPE_REGISTRY" ]; then
Could you remind where is this handled currently?

2025-01-02 18:20 UTC, kachawla commented on test/execute-functional-tests-cloud.sh
> +# If not, create one using `rad env create default`.
This script seems to be creating group and env below L30-L32, so why is this manual check needed?

2025-01-02 18:20 UTC, kachawla commented on test/execute-functional-tests-cloud.sh
> +# To run functional tests, you have to be in `kind-radius` group and
Could you share context on why this is the case?

2025-01-02 18:20 UTC, kachawla commented on test/execute-functional-tests-cloud.sh
> +rad group create kind-radius
Why does it need to create two groups?

2025-01-02 18:20 UTC, kachawla commented on test/testrecipes/test-terraform-recipes/README.md
> +---
What does this update do?

2025-01-02 18:42 UTC, ytimocin commented on test/testrecipes/test-terraform-recipes/README.md
> +---
This is a refactoring of the README.md. That extra `-` was unnecessary and "shift + opt + F" in VS Code cleans it up.

2025-01-02 18:43 UTC, ytimocin commented on test/execute-functional-tests-cloud.sh
> +if [ -z "$BICEP_RECIPE_REGISTRY" ]; then
This is not being handled anywhere currently in the helper script.

2025-01-02 18:45 UTC, ytimocin commented on .github/workflows/functional-test-noncloud.yaml
> -          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
This **yaml** is for non-cloud tests. If you see [the references of **GH_TOKEN**](https://github.com/search?q=repo%3Aradius-project%2Fradius%20%22GetGitPAT%22&type=code), you can see that it is only being used in a cloud test.

2025-01-02 18:46 UTC, ytimocin commented on test/execute-functional-tests-cloud.sh
> +# To run functional tests, you have to be in `kind-radius` group and
Because we have some hard-coded environment names in our functional tests: https://github.com/search?q=repo%3Aradius-project%2Fradius+%22kind-radius%22&type=code.

2025-01-02 18:47 UTC, ytimocin commented on test/execute-functional-tests-cloud.sh
> +rad group create kind-radius
Please see: https://github.com/search?q=repo%3Aradius-project%2Fradius+%22kind-radius%22&type=code.

2025-01-02 18:47 UTC, ytimocin commented on test/execute-functional-tests-cloud.sh
> +# If not, create one using `rad env create default`.
Just being extra defensive.

2025-01-02 18:48 UTC, ytimocin commented on .github/workflows/functional-test-cloud.yaml
> +
This is a refactoring of the **functional-test-cloud.yaml** file. Not an extension but built-in feature ("shift + opt + F") in VS Code cleans it up.

2025-01-02 18:48 UTC, ytimocin commented on .github/workflows/functional-test-cloud.yaml
> +  BICEP_TYPES_REGISTRY: "biceptypes.azurecr.io"
This is a refactoring of the **functional-test-cloud.yaml** file. Not an extension but built-in feature ("shift + opt + F") in VS Code cleans it up.

2025-01-03 00:03 UTC, kachawla commented on test/execute-functional-tests-cloud.sh
> +# To run functional tests, you have to be in `kind-radius` group and
Can you update the comment to include the context?

2025-01-03 00:04 UTC, kachawla commented on test/execute-functional-tests-cloud.sh
> +rad group create kind-radius
The link you referenced points to all occurrences of `kind-radius` - can you help me understand how does that result into requiring two groups to be created?

2025-01-03 00:04 UTC, kachawla commented on test/execute-functional-tests-cloud.sh
> +# If not, create one using `rad env create default`.
That seems unnecessary here.

2025-01-03 00:05 UTC, kachawla commented on test/execute-functional-tests-cloud.sh
> +if [ -z "$BICEP_RECIPE_REGISTRY" ]; then
How's everyone running functional tests today? Is this documented somewhere for manual setup?

2025-01-13 16:11 UTC, ytimocin commented on test/execute-functional-tests-cloud.sh
> +rad group create kind-radius
For example, in this [test](https://github.com/radius-project/radius/blob/main/test/functional-portable/corerp/noncloud/resources/recipe_terraform_test.go#L64) we have hard-coded the group called kind-radius. And if you run the functional tests in your local without creating kind-radius group, you will see that some tests will fail.

Yes, the link I referenced points to all occurrences of `kind-radius`. If you go over the list, you will see that most of them are in the functional tests' territory.

2025-01-13 16:16 UTC, ytimocin commented on test/execute-functional-tests-cloud.sh
> +if [ -z "$BICEP_RECIPE_REGISTRY" ]; then
🤷‍♂️

2025-01-13 16:16 UTC, ytimocin commented on test/execute-functional-tests-cloud.sh
> +if [ -z "$BICEP_RECIPE_REGISTRY" ]; then
I am trying to update the document with this PR.

2025-01-13 16:22 UTC, ytimocin commented on docs/contributing/contributing-code/contributing-code-tests/running-functional-tests.md
> +1. Required environment variables:
I added descriptions for these environment variables.

2025-01-13 16:23 UTC, ytimocin commented on docs/contributing/contributing-code/contributing-code-control-plane/running-controlplane-locally.md
>  workspaces:
We can do both ways. This doc was written before, so I am not going to touch that part of the information. We can update later if necessary.

2025-01-14 14:26 UTC, brooke-hamilton commented on docs/contributing/contributing-code/contributing-code-control-plane/running-controlplane-locally.md
> +
Our docs say to use the configuration below when creating a Kind cluster, but this configuration causes port conflicts when launching the debugger.

```yaml
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
- role: worker
  extraPortMappings:
  - containerPort: 80
    hostPort: 8080
    listenAddress: "0.0.0.0"  
  - containerPort: 443
    hostPort: 8443
    listenAddress: "0.0.0.0"
```

2025-01-14 14:33 UTC, brooke-hamilton commented on docs/contributing/contributing-code/contributing-code-tests/running-functional-tests.md
> +   3. **BICEP_RECIPE_REGISTRY**: This is the container registry that you would be using for storing the Bicep recipes.
Are these URLs or registry names?

2025-01-14 17:28 UTC, kachawla commented on test/execute-functional-tests-cloud.sh
> +rad env create kind-radius
The `kind-radius` environment is created in `kind-radius` group here https://github.com/radius-project/radius/blob/main/.github/workflows/functional-test-noncloud.yaml#L293-L299. Any reason to create it in the default group locally?

2025-01-14 17:29 UTC, kachawla commented on test/execute-functional-tests-cloud.sh
> +# `rad env list` and check if there is an environment named `default`.
If this is expected to be already existing, then the manual group creation on L30 shouldn't be needed

2025-01-14 17:38 UTC, kachawla commented on docs/contributing/contributing-code/contributing-code-tests/running-functional-tests.md
> +   1. **TF_RECIPE_MODULE_SERVER_URL**: This is the URL for the Terraform Recipe Module Server. If you have run `make publish-test-terraform-recipes` you will see this URL at the end of that command.
Running `make publish-test-terraform-recipes` is a prerequisite so let's make that explicit. Feel free to modify the suggested phrasing. Also, let's call it out in the prerequisite above to copy the output for later use.

```suggestion
   1. **TF_RECIPE_MODULE_SERVER_URL**: This is the URL for the Terraform Recipe Module Server. You can find this URL in the output of `make publish-test-terraform-recipes` from step 7 of prerequisite above.
```

2025-01-14 17:40 UTC, kachawla commented on docs/contributing/contributing-code/contributing-code-tests/running-functional-tests.md
> +   2. **DOCKER_REGISTRY**: This is the container registry that you would be using for storing the test related images.
Is this required or do we have a default that we can point the users to?

2025-01-14 17:41 UTC, kachawla commented on docs/contributing/contributing-code/contributing-code-tests/running-functional-tests.md
> +   3. **BICEP_RECIPE_REGISTRY**: This is the container registry that you would be using for storing the Bicep recipes.
Same here, is this required or optional? Do we have a default in either case?

2025-01-14 17:45 UTC, kachawla commented on docs/contributing/contributing-code/contributing-code-tests/running-functional-tests.md
> +   4. **RADIUS_SAMPLES_REPO_ROOT**: This should point to the root directory of the Samples repository in your local, if you want to run the functional tests for the samples.
> if you want to run the functional tests for the samples

What happens if this is not set?

2025-01-14 17:49 UTC, kachawla commented on docs/contributing/contributing-code/contributing-code-tests/running-functional-tests.md
> +1. Required environment variables:
Are all of these env variables required or some are optional?

2025-01-14 17:50 UTC, kachawla commented on docs/contributing/contributing-code/contributing-code-tests/running-functional-tests.md
> +2. Run:
Let's expand on this to give user some context on what's going to happen when they run this script.

2025-01-14 18:26 UTC, kachawla commented on test/execute-functional-tests-noncloud.sh
> +# `make test-functional-all-noncloud`
Same here

2025-01-14 18:26 UTC, kachawla commented on test/execute-functional-tests-noncloud.sh
> +cd ../
Is this needed in the cloud tests script as well?

2025-01-14 18:26 UTC, kachawla commented on test/execute-functional-tests-noncloud.sh
> +make test-functional-samples-noncloud
Do we need users to run samples in local testing?

2025-01-14 18:26 UTC, kachawla commented on test/execute-functional-tests-noncloud.sh
> +# make test-functional-corerp-noncloud
Shouldn't be commented out?

2025-02-24 22:24 UTC, kachawla reviewed
@ytimocin Is this ready for re-review since last set of comments?

2025-06-02 18:09 UTC, closed without merging