Add test documentation
radius-project/radius pull request #81
Opened 2021-03-12 18:49 UTC by vinayada1

Add docs related to running and maintaining tests

2021-03-12 19:54 UTC, kachawla approved these changes

2021-03-15 19:01 UTC, AaronCrawfis requested changes

2021-03-16 00:50 UTC, AaronCrawfis requested changes
Couple small header changes. Additionally, please create a file named `_index.md` in the docs/content/developing/tests/ directory with the following content:

```
---
type: docs
title: "Running tests during Radius development"
linkTitle: "Tests"
description: "How to run deploy tests and e2e tests when developing Radius"
weight: 80
---
```

2021-03-16 01:05 UTC, AaronCrawfis approved these changes
Thanks so much!

2021-03-16 01:08 UTC, merged