add create resource type command
radius-project/radius pull request #8104
Opened 2024-12-03 20:42 UTC by nithyatsu

# Description

_Please explain the changes you've made._

## Type of change

- This pull request fixes a bug in Radius and has an approved issue (issue link required).
- This pull request adds or changes features of Radius and has an approved issue (issue link required).
- This pull request is a minor refactor, code cleanup, test improvement, or other maintenance task and doesn't change the functionality of Radius (issue link optional).

Fixes: #issue_number

## Contributor checklist
Please verify that the PR meets the following requirements, where applicable:

- [ ] An overview of proposed schema changes is included in a linked GitHub issue.
- [ ] A design document PR is created in the [design-notes repository](https://github.com/radius-project/design-notes/), if new APIs are being introduced.
- [ ] If applicable, design document has been reviewed and approved by Radius maintainers/approvers.
- [ ] A PR for the [samples repository](https://github.com/radius-project/samples) is created, if existing samples are affected by the changes in this PR.
- [ ] A PR for the [documentation repository](https://github.com/radius-project/docs) is created, if the changes in this PR affect the documentation or any user facing updates are made.
- [ ] A PR for the [recipes repository](https://github.com/radius-project/recipes) is created, if existing recipes are affected by the changes in this PR.

2025-01-07 04:06 UTC, ytimocin requested changes

2025-01-07 04:06 UTC, ytimocin commented on pkg/cli/cmd/resourcetype/create/create.go
> +	response, err := r.UCPClientFactory.NewResourceTypesClient().Get(ctx, "local", r.ResourceProvider.Name, r.ResourceTypeName, nil)
This is a ResourceTypesClient not a ResourceProvidersClient. The comment says that if the resource provider doesn't exist first create it.

Either the comment is wrong or the created client...

2025-01-07 04:06 UTC, ytimocin commented on pkg/cli/cmd/resourcetype/create/create_test.go
> +		},
We should add the case where resource provider doesn't exist, and the code creates that first. If that is going to be one of the cases that will be handled per the comment in the **create.go**.

2025-01-07 04:06 UTC, ytimocin commented on pkg/cli/cmd/resourcetype/create/create_test.go
> +
nit: remove extra line

2025-01-07 04:06 UTC, ytimocin commented on pkg/cli/manifest/registermanifest.go
> +	//set it back to resource provider
```suggestion
	// Set it back to resource provider
```

2025-01-07 04:06 UTC, ytimocin commented on pkg/cli/manifest/registermanifest.go
> +	//set it back to resource provider
I don't think we need the comment.

2025-01-07 04:06 UTC, ytimocin commented on pkg/cli/manifest/testclientfactory.go
> +	//(ctx, planeName, resourceProvider.Name, v1.LocationGlobal, nil)
Is this to be commented out?

2025-01-07 16:34 UTC, nithyatsu commented on pkg/cli/clivalidation.go
> +
I followed the format for rest of the file. I am not sure of the reason. for ex: 
```
// ReadResourceGroupNameArgs is used to get the resource group name that is supplied as either the first argument for group commands or using a -g flag
//

// ReadResourceGroupNameArgs reads a resource group name from either a command flag or an argument, and returns an error if
//
//	both are specified.
```

2025-01-07 16:38 UTC, nithyatsu commented on pkg/cli/clivalidation.go
> +func RequireResourceTypeNameArgs(cmd *cobra.Command, args []string) (string, error) {
makes sense to me, but  ReadResourceGroupNameArgs, RequireRecipeNameArgs expect just one arg too. Perhaps we are just refering to the args as typical name of the arguments array?

2025-01-07 16:47 UTC, nithyatsu commented on pkg/cli/clivalidation.go
> +func ReadResourceTypeNameArgs(cmd *cobra.Command, args []string) (string, error) {
please read my reason above.

2025-01-07 16:51 UTC, nithyatsu commented on pkg/cli/manifest/testclientfactory.go
> +	//(ctx, planeName, resourceProvider.Name, v1.LocationGlobal, nil)
removed the comments

2025-01-07 18:50 UTC, nithyatsu commented on pkg/cli/cmd/resourcetype/create/create_test.go
> +		},
added one. its tricky to test end to end, since we either mock a server that returns error or success. The two tests, one which uses a successresponse server and the other which uses error response should cover the flows.

2025-01-07 18:56 UTC, nithyatsu commented on pkg/cli/cmd/resourcetype/create/create.go
> +// Runner is the Runner implementation for the `rad resourceprovider create` command.
@Reshrahim can perhaps clarify. and add to documentation comments.

2025-01-07 19:10 UTC, Reshrahim commented on pkg/cli/cmd/resourcetype/create/create.go
> +// Runner is the Runner implementation for the `rad resourceprovider create` command.
yes it is rad resource-provider and rad resource-type. @nithyatsu - can you do a scrub of the old texts and update them.

2025-01-07 21:57 UTC, nithyatsu commented on pkg/cli/cmd/resourcetype/create/create.go
> +// Runner is the Runner implementation for the `rad resourceprovider create` command.
done

2025-01-07 22:19 UTC, ytimocin commented on pkg/cli/cmd/resourcetype/create/create.go
> +	if err != nil {
The error can also be something other than `Resource Provider not Found`, right?

2025-01-07 22:35 UTC, nithyatsu commented on pkg/cli/cmd/resourcetype/create/create.go
> +	if err != nil {
yes. Currently, if there are errors, approach is to recreate. @rynowak do you see any problems with this approach?

2025-01-08 18:25 UTC, ytimocin commented on pkg/cli/cmd/resourcetype/create/create.go
> +	if err != nil {
I think we should only create if the error is 404 and fail if it is something else.

2025-01-08 18:25 UTC, ytimocin commented on pkg/cli/cmd/resourcetype/create/create_test.go
> +	// another test for failure
this can be removed

2025-01-08 18:25 UTC, ytimocin commented on pkg/cli/manifest/registermanifest.go
> +	// Check for valid file path
These comments can be removed since the code is pretty clear.

2025-01-08 21:21 UTC, nithyatsu commented on pkg/cli/cmd/resourcetype/create/create.go
> +	if err != nil {
Added changes to return error if it is not 404.

2025-01-08 21:21 UTC, nithyatsu commented on pkg/cli/cmd/resourcetype/create/create.go
> +	if err != nil {
> I think we should only create if the error is 404 and fail if it is something else.

Added changes to return error if it is not 404.

2025-01-08 22:02 UTC, ytimocin submitted a review, later dismissed

2025-01-08 22:03 UTC, ytimocin commented on pkg/cli/cmd/resourcetype/create/create.go
> +	// Add a blank line before printing the result.
nit: remove

2025-01-08 22:03 UTC, ytimocin commented on pkg/cli/manifest/registermanifest.go
> +	// get the existing location resource and update it with new resource type. We have to revisit this code once schema is finalized and validated.
nit: remove

2025-01-08 22:15 UTC, lakshmimsft commented on pkg/cli/manifest/testclientfactory.go
> +func NewTestClientFactory(resourceProvidersServer func() ucpfake.ResourceProvidersServer) (*v20231001preview.ClientFactory, error) {
Question on updated function signature. Do we feel this will need updated soon. Eg. we want ResourceTypesServer/Locations server returning error but not resourceproviderserver etc. Let's discuss.

2025-01-08 22:20 UTC, lakshmimsft commented on pkg/cli/manifest/registermanifest.go
> +		defaultAPIVersion = "2023-10-01-preview" //hardcoded for now, since we don't have a default API version in the manifest but it should be made mandatory as part of schema validation
can we move this to a const or use v20231001preview.Version instead

2025-01-08 22:31 UTC, lakshmimsft commented on pkg/cli/manifest/registermanifest.go
> +	locationResource.Properties.ResourceTypes[typeName] = &v20231001preview.LocationResourceType{
cool!

2025-01-08 22:56 UTC, nithyatsu commented on pkg/cli/manifest/registermanifest.go
> +	// get the existing location resource and update it with new resource type. We have to revisit this code once schema is finalized and validated.
I think this comment is useful because it indicates revisiting the code once schema validation comes in.

2025-01-08 22:58 UTC, nithyatsu commented on pkg/cli/manifest/testclientfactory.go
> +func NewTestClientFactory(resourceProvidersServer func() ucpfake.ResourceProvidersServer) (*v20231001preview.ClientFactory, error) {
discussed offline. the code will likely evolve to support more cases and at that point it might be useful to bring in a factory for each resource.

2025-01-08 23:01 UTC, lakshmimsft approved these changes

2025-01-08 23:27 UTC, merged